# File: .github/workflows/publish.yml
name: publish methxsort package

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0
  release:
    types: [published]  # Triggers when a new release is published on GitHub

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:        # ✅ REQUIRED for OIDC / Trusted Publishing
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build
        pip install setuptools 

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      # with:
      #   password: ${{ secrets.PYPI_API_TOKEN }}

